### ISSUE TITLE
Publish to JCenter

### ISSUE THREAD

**Issue by daspilker** [kohsuke/localizer#12]
The [Gradle JPI plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+JPI+Plugin) depends on localizer. Gradle plugins published through the Gradle Plugin Portal must should/must have their dependencies available on JCenter. The latest version on JCenter is 1.19, but I need 1.20 or later to get the JavaDoc fixes for Java 8.

Using dependencies outside of JCenter forces a verbose Gradle build file syntax:

```
buildscript {
    repositories {
        jcenter()
        maven {
            url('https://repo.jenkins-ci.org/releases/')
        }
    }
    dependencies {
        classpath 'org.jenkins-ci.tools:gradle-jpi-plugin:0.18.1'
    }
}

apply plugin: 'org.jenkins-ci.jpi'
```

instead of just 

```
plugins {
    id 'org.jenkins-ci.jpi' version '0.18.1'
}
```

In order to publish to JCenter, the artifacts must be upload to Bintray from where they can be promoted to JCenter, see https://bintray.com/docs/usermanual/uploads/uploads_promotingyourmaterial.html.

**Comment by kohsuke** [comment]
Started working on issue #7 which achieves the same goal
