### ISSUE TITLE
Publish new localizer to Maven central repository?

### ISSUE THREAD

**Issue by tan9** [kohsuke/localizer#7]
Dear Kohsuke,

Can you publish this artifact to maven central repository?
Current version in maven central is really old (1.12 released in 2010).

This can ease to effort for developers who using localizer (no extra `repository`, `pluginRepository` settings in pom.xml).
And promote others to use this fancy tool!

**Comment by kohsuke** [comment]
I filed https://issues.sonatype.org/browse/OSSRH-26780

**Comment by GheRivero** [comment]
This plugin is neither up to date in jcenter or mavencentral

**Comment by timja** [comment]
@kohsuke  did you want to publish this? or should we look to move this to jenkinsci?

**Comment by kohsuke** [comment]
I believe I just successfully released 1.31. Like other projects of mine, if the Jenkins org will take a better care of it, I'm happy to transfer this as well. Please let me know how the team wants me to do.
